/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAssinaturaRouteImport } from './routes/_authenticated/assinatura'
import { Route as AuthenticatedCompletarPerfilRouteImport } from './routes/_authenticated/completar-perfil'
import { Route as AuthenticatedFaleConoscoRouteImport } from './routes/_authenticated/fale-conosco'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedConfirmarSessionIdRouteImport } from './routes/_authenticated/confirmar.$sessionId'
import { Route as AuthenticatedPacientesIndexRouteImport } from './routes/_authenticated/pacientes.index'
import { Route as AuthenticatedPacientesIdRouteImport } from './routes/_authenticated/pacientes.$id'
import { Route as ApiPublicCaktoWebhookRouteImport } from './routes/api/public/cakto-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssinaturaRoute = AuthenticatedAssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompletarPerfilRoute =
  AuthenticatedCompletarPerfilRouteImport.update({
    id: '/completar-perfil',
    path: '/completar-perfil',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFaleConoscoRoute =
  AuthenticatedFaleConoscoRouteImport.update({
    id: '/fale-conosco',
    path: '/fale-conosco',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfirmarSessionIdRoute =
  AuthenticatedConfirmarSessionIdRouteImport.update({
    id: '/confirmar/$sessionId',
    path: '/confirmar/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPacientesIndexRoute =
  AuthenticatedPacientesIndexRouteImport.update({
    id: '/pacientes/',
    path: '/pacientes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPacientesIdRoute =
  AuthenticatedPacientesIdRouteImport.update({
    id: '/pacientes/$id',
    path: '/pacientes/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCaktoWebhookRoute = ApiPublicCaktoWebhookRouteImport.update({
  id: '/api/public/cakto-webhook',
  path: '/api/public/cakto-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/app': typeof AuthenticatedAppRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/completar-perfil': typeof AuthenticatedCompletarPerfilRoute
  '/fale-conosco': typeof AuthenticatedFaleConoscoRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/confirmar/$sessionId': typeof AuthenticatedConfirmarSessionIdRoute
  '/pacientes/$id': typeof AuthenticatedPacientesIdRoute
  '/api/public/cakto-webhook': typeof ApiPublicCaktoWebhookRoute
  '/pacientes/': typeof AuthenticatedPacientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/app': typeof AuthenticatedAppRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/completar-perfil': typeof AuthenticatedCompletarPerfilRoute
  '/fale-conosco': typeof AuthenticatedFaleConoscoRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/confirmar/$sessionId': typeof AuthenticatedConfirmarSessionIdRoute
  '/pacientes/$id': typeof AuthenticatedPacientesIdRoute
  '/api/public/cakto-webhook': typeof ApiPublicCaktoWebhookRoute
  '/pacientes': typeof AuthenticatedPacientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/assinatura': typeof AuthenticatedAssinaturaRoute
  '/_authenticated/completar-perfil': typeof AuthenticatedCompletarPerfilRoute
  '/_authenticated/fale-conosco': typeof AuthenticatedFaleConoscoRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/confirmar/$sessionId': typeof AuthenticatedConfirmarSessionIdRoute
  '/_authenticated/pacientes/$id': typeof AuthenticatedPacientesIdRoute
  '/api/public/cakto-webhook': typeof ApiPublicCaktoWebhookRoute
  '/_authenticated/pacientes/': typeof AuthenticatedPacientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/agenda'
    | '/app'
    | '/assinatura'
    | '/completar-perfil'
    | '/fale-conosco'
    | '/financeiro'
    | '/perfil'
    | '/confirmar/$sessionId'
    | '/pacientes/$id'
    | '/api/public/cakto-webhook'
    | '/pacientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/agenda'
    | '/app'
    | '/assinatura'
    | '/completar-perfil'
    | '/fale-conosco'
    | '/financeiro'
    | '/perfil'
    | '/confirmar/$sessionId'
    | '/pacientes/$id'
    | '/api/public/cakto-webhook'
    | '/pacientes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/agenda'
    | '/_authenticated/app'
    | '/_authenticated/assinatura'
    | '/_authenticated/completar-perfil'
    | '/_authenticated/fale-conosco'
    | '/_authenticated/financeiro'
    | '/_authenticated/perfil'
    | '/_authenticated/confirmar/$sessionId'
    | '/_authenticated/pacientes/$id'
    | '/api/public/cakto-webhook'
    | '/_authenticated/pacientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicCaktoWebhookRoute: typeof ApiPublicCaktoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assinatura': {
      id: '/_authenticated/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AuthenticatedAssinaturaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/completar-perfil': {
      id: '/_authenticated/completar-perfil'
      path: '/completar-perfil'
      fullPath: '/completar-perfil'
      preLoaderRoute: typeof AuthenticatedCompletarPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fale-conosco': {
      id: '/_authenticated/fale-conosco'
      path: '/fale-conosco'
      fullPath: '/fale-conosco'
      preLoaderRoute: typeof AuthenticatedFaleConoscoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/confirmar/$sessionId': {
      id: '/_authenticated/confirmar/$sessionId'
      path: '/confirmar/$sessionId'
      fullPath: '/confirmar/$sessionId'
      preLoaderRoute: typeof AuthenticatedConfirmarSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pacientes/': {
      id: '/_authenticated/pacientes/'
      path: '/pacientes'
      fullPath: '/pacientes/'
      preLoaderRoute: typeof AuthenticatedPacientesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pacientes/$id': {
      id: '/_authenticated/pacientes/$id'
      path: '/pacientes/$id'
      fullPath: '/pacientes/$id'
      preLoaderRoute: typeof AuthenticatedPacientesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cakto-webhook': {
      id: '/api/public/cakto-webhook'
      path: '/api/public/cakto-webhook'
      fullPath: '/api/public/cakto-webhook'
      preLoaderRoute: typeof ApiPublicCaktoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedAssinaturaRoute: typeof AuthenticatedAssinaturaRoute
  AuthenticatedCompletarPerfilRoute: typeof AuthenticatedCompletarPerfilRoute
  AuthenticatedFaleConoscoRoute: typeof AuthenticatedFaleConoscoRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedConfirmarSessionIdRoute: typeof AuthenticatedConfirmarSessionIdRoute
  AuthenticatedPacientesIdRoute: typeof AuthenticatedPacientesIdRoute
  AuthenticatedPacientesIndexRoute: typeof AuthenticatedPacientesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedAssinaturaRoute: AuthenticatedAssinaturaRoute,
  AuthenticatedCompletarPerfilRoute: AuthenticatedCompletarPerfilRoute,
  AuthenticatedFaleConoscoRoute: AuthenticatedFaleConoscoRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedConfirmarSessionIdRoute: AuthenticatedConfirmarSessionIdRoute,
  AuthenticatedPacientesIdRoute: AuthenticatedPacientesIdRoute,
  AuthenticatedPacientesIndexRoute: AuthenticatedPacientesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicCaktoWebhookRoute: ApiPublicCaktoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
